@echo off
echo ======== START ========
echo Starting at %DATE% %TIME%...
echo Creating output folders...
if not exist tmp mkdir tmp
if not exist out mkdir out
echo Preprocessing...
gcc -E -x c src\pkp.pnml -o tmp\pkp-set.nml
echo Compiling...
nmlc -c --grf out\polish-rolling-stock-pack-0.15.5.grf tmp\pkp-set.nml
echo ========= END =========